version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "face-rec"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1tsc5g5rujv9x"
s3_prefix = "face-rec"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=290612617581.dkr.ecr.us-east-1.amazonaws.com/face-rec-ecr"]
